### ISSUE TITLE
Supports for Multi-shot Algorithms?

### ISSUE THREAD

**Issue by dosydon** [potassco/plasp#5]
In Section 3 of the paper "plasp 3: Towards Effective ASP Planning", several strategies for fixing the plan length are described. Does this code repository support multi-shot algorithms such as "algorithm A" and "algorithm B" described in the paper? 

As far as I can tell, the code base supports parallel encoding variants using encodings in (https://github.com/potassco/plasp/tree/master/encodings/strips). But the strategy for fixing the plan length is limited to the "sequential strategy".

**Comment by pluehne** [comment]
Thanks for reaching out and your interest in plasp 😃!

You’ve pointed out correctly that as of now, this repository contains the *translation* part of plasp and some PDDL-related tools. The *planning algorithms* A and B are currently maintained by @javier-romero in [another repository](https://github.com/javier-romero/plasp/tree/master/encodings/planner). You might want to look there for the actual planner.

If you have further questions, feel free to ask @javier-romero or me!

**Comment by dosydon** [comment]
Thanks very much!
