### ISSUE TITLE
Question regarding reproducing the results in the paper "plasp 3: Towards Effective ASP Planning"?

### ISSUE THREAD

**Issue by dosydon** [potassco/plasp#6]
I'm trying to reproduce the Table 1 and 2 in the paper "plasp 3: Towards Effective ASP Planning". Thanks to the helpful README, I've been able to more or less figure out how to invoke the command line interface to reproduce the configurations in the paper, but not too sure if I'm correct. It would be great if someone can help me on this. Please allow me to post an issue here as I wasn't able to post an issue on the forked repository (https://github.com/javier-romero/plasp).

Here's what I've figured out so far for Table 1:

|Configuration | Command|
|------------------|---------------|
|B^∃_p| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -B=0.9 -m 8000 --use-heuristic|
|B^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -B=0.9 -m 8000|
|A^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -A=16 -m 8000 |
|B^E| runplanner.py PROBLEM --domain DOMAIN --parallel=3 --postprocess -B=0.9 -m 8000|
|B^R| runplanner.py PROBLEM --domain DOMAIN --parallel=4 --postprocess -B=0.9 -m 8000|
|B^S| runplanner.py PROBLEM --domain DOMAIN --parallel=5 --postprocess -B=0.9 -m 8000|
|B^∀| runplanner.py PROBLEM --domain DOMAIN --parallel=1 --postprocess -B=0.9 -m 8000|
|S^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -A=1 -m 8000|

Here's what I've figured out so far for Table 2:

|Configuration | Command|
|------------------|---------------|
|B^∃_p| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -B=0.9 -m 8000 --use-heuristic --translate|
|B^E| runplanner.py PROBLEM --domain DOMAIN --parallel=3 --postprocess -B=0.9 -m 8000 --translate|
|B^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -B=0.9 -m 8000 --translate|
|A^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -A=16 -m 8000 --translate|
|B^∀| runplanner.py PROBLEM --domain DOMAIN --parallel=1 --postprocess -B=0.9 -m 8000 --translate|
|B^R| runplanner.py PROBLEM --domain DOMAIN --parallel=4 --postprocess -B=0.9 -m 8000 --translate|
|S^∃| runplanner.py PROBLEM --domain DOMAIN --parallel=2 --postprocess -A=1 -m 8000 --translate|
|B^S| runplanner.py PROBLEM --domain DOMAIN --parallel=5 --postprocess -B=0.9 -m 8000  --translate|

Plus, it would be interesting to know how exactly wallclock time limit was set for the experiments in the paper.

**Comment by pluehne** [comment]
Please excuse me for not having had the time to respond yet due to the Christmas break. I’ll give you the exact commands to reproduce the results in the paper later today. If I forget about it, feel free to bump this thread until I do 😃. And if you need further information, just let me know.

And thanks again for your interest in `plasp`!

**Comment by pluehne** [comment]
You almost got the configurations right :slightly_smiling_face:. The basic planner call in our experiments consists of:

```sh
runplanner.py --domain=<domain file> <instance file> --stats --verbose --print-call
```

where the three shown options are for debugging purposes, and additional options are set depending on the configuration. I admit that the mapping from configuration names to `runplanner` options (and the naming of the options) is confusing. Your configurations looks right except for the values of `--parallel`. For the sake of completeness and for future reference, here is the full mapping between the terminology used in the paper and the `runplanner.py` options:

| planning algorithm | additional option |
|---|---|
| S | `-A 1` |
| A | `-A 16` |
| B | `-B 0.9` |

| encoding | additional option |
|---|---|
| ∀ | `--parallel=1` |
| R | `--parallel=2` |
| ∃ | `--parallel=3` |
| E | `--parallel=4` |

| heuristics (_p) | additional option |
|---|---|
| enabled | `--use-heuristic` |
| disabled | — |

| preprocessing | additional option |
|---|---|
| none | — |
| FastDownward | `--translate` |

For time and memory limits, I used [`timeout`](https://github.com/pshved/timeout) by Pavel Shved with the `-t` and `-m` options. However, if I had to do it again, I would probably opt for something based on `cgroups`, as the author of `timeout` suggests as well.

For instance, the complete call for B^∃ with preprocessing by FastDownward looks like:

```sh
timeout -t=900 -m=8000000 python runplanner.py --domain=<domain file> <instance file> --stats --verbose --print-call -B 0.9 --parallel=3 --use-heuristic --translate
```

I hope this clarifies your questions on reproducing our experiments :slightly_smiling_face:. If not, just drop me another comment here!

Some minor notes:

- The `-m` option given to `timeout` is separate from the `-m` option to `runplanner.py`, which is just a recommendation or memory usage guideline but not a hard limit as of the current implementation.
- `--use-heuristic` applies the heuristics in exactly the same as in the paper, although the option was set differently at the time of writing the paper.

**Comment by dosydon** [comment]
Thanks! This helped me a lot. Closing the issue.

**Comment by pluehne** [comment]
Happy to help! If you have further questions or ideas, I’d be curious to hear about them 🙂!
