### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by vstylianos** [potassco/plasp#7]
Hi, I'm trying to build plasp but I'm getting the following error when I'm trying to make the module and cannot figure out the reason why. Any help will be much appreciated!

/Library/Developer/CommandLineTools/usr/include/c++/v1/experimental/optional:163:4: error: 
      "<experimental/optional> is deprecated and will be removed in the next
      release. Please use C++17's <optional> instead." [-Werror,-W#warnings]
 warning "<experimental/optional> is deprecated and will be removed i...
   ^
In file included from /Users/thestlucas/Desktop/ASP_explainability/plasp/lib/pddl/src/pddl/Parse.cpp:1:
In file included from /Users/thestlucas/Desktop/ASP_explainability/plasp/lib/pddl/include/pddl/Parse.h:6:
In file included from /Users/thestlucas/Desktop/ASP_explainability/plasp/lib/pddl/include/pddl/ASTForward.h:10:
/Users/thestlucas/Desktop/ASP_explainability/plasp/lib/pddl/include/pddl/Variant.h:4:10: fatal error: 
      'mapbox/variant.hpp' file not found
#include <mapbox/variant.hpp>
         ^~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [lib/pddl/src/CMakeFiles/pddl.dir/pddl/Parse.cpp.o] Error 1
make[1]: *** [lib/pddl/src/CMakeFiles/pddl.dir/all] Error 2
make: *** [all] Error 2

**Comment by jcsi225** [comment]
I'm getting the <mapbox/variant.hpp> error too.

**Comment by pluehne** [comment]
Sorry for the long turnaround. That’s most likely because of extended C++ language support by more recent GCC and Clang versions. I may have to write a fix for that, and I’ll try to do that as soon as I have the time.

**Comment by pluehne** [comment]
@TheStLucas, @jcsi225: Can you point out which compiler version you’re using? I can’t reproduce this exact issue with Clang 9.0.1 and `g++` 9.3.0.

**Comment by jcsi225** [comment]
Thanks for having a look at this! I'm using g++ 7.4.0.

**Comment by pluehne** [comment]
@jcsi225: Are you on macOS? The explanation could be that I’m building against `libstdc++`, while the error message posted by @TheStLucas seems to be related to `libc++`. Dou you know which of the two you’re using?

**Comment by jcsi225** [comment]
I'm on Linux --- I'm not certain, but I think that means I have `libstdc++`. The equivalent error message I'm getting is:

> In file included from /plasp/lib/pddl/include/pddl/ASTForward.h:10:0,
>                  from /plasp/lib/pddl/include/pddl/Parse.h:6,
>                  from /plasp/lib/pddl/src/pddl/Parse.cpp:1:
> /plasp/lib/pddl/include/pddl/Variant.h:4:10: fatal error: mapbox/variant.hpp: No such file or directory
>  #include <mapbox/variant.hpp>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> lib/pddl/src/CMakeFiles/pddl.dir/build.make:62: recipe for target 'lib/pddl/src/CMakeFiles/pddl.dir/pddl/Parse.cpp.o' failed
> make[2]: *** [lib/pddl/src/CMakeFiles/pddl.dir/pddl/Parse.cpp.o] Error 1
> CMakeFiles/Makefile2:194: recipe for target 'lib/pddl/src/CMakeFiles/pddl.dir/all' failed
> make[1]: *** [lib/pddl/src/CMakeFiles/pddl.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by pluehne** [comment]
Oh, you may just be missing the `mapbox` submodule.

Did you run

```sh
$ git submodule update --init --recursive
```

after cloning? If not, the `mapbox` directory, which is a dependency of `plasp` as of now and populated by a Git submodule will be empty. Let me know if that’s all there is to the issue you’re seeing.

**Comment by jcsi225** [comment]
Oops, that was it. Thank you!

**Comment by pluehne** [comment]
@TheStLucas: I was distracted by the warning about experimental language features, so I missed the part where the submodule wasn’t initialized. Can you check whether the same solution that helped @jcsi225 also works for you?

**Comment by pluehne** [comment]
@TheStLucas: Rereading the error message, I’m almost 100 % sure that it’s just the `variant` submodule that’s missing. I’m going to close this one assuming that’s the case, but feel free to comment here if you need further help.
